# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rn578' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'BatchedBridge',
    'RCTImage',
    'DevSupport',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTLinkingIOS',
  ]
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  # Pods for rn578
  pod 'appcenter', path: '../node_modules/appcenter/ios'
  pod 'appcenter-analytics', path: '../node_modules/appcenter-analytics/ios'

  target 'rn578-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rn578Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

